import Ionicons from '@expo/vector-icons/Ionicons';
import { FlashList } from '@shopify/flash-list';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { useTheme } from '@/theme';

import licences from './licences.json';

type Licence = (typeof licences.packages)[number];

const MONOSPACE = Platform.select({ ios: 'Menlo', default: 'monospace' });

/**
 * Open-source licences (About → Open-source licences): every package inside the app, with its
 * licence text, which MIT, BSD and Apache ask to travel with the app. The list is generated by
 * `npm run build:licences` (scripts/build-licences) — run it after changing libraries.
 * Licence texts are shown as written, in English: they are legal text, not app wording.
 */
export function LicencesScreen() {
  const { t } = useTranslation();
  const { colors, spacing, fontSize, radius, minTapTarget } = useTheme();
  const [open, setOpen] = useState<ReadonlySet<string>>(new Set());

  const toggle = (name: string) =>
    setOpen((current) => {
      const next = new Set(current);
      if (next.has(name)) next.delete(name);
      else next.add(name);
      return next;
    });

  const renderItem = ({ item }: { item: Licence }) => {
    const expanded = open.has(item.name);
    const text = item.text === null ? null : licences.texts[item.text];
    return (
      <View style={{ borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.border }}>
        <Pressable
          accessibilityRole="button"
          accessibilityState={{ expanded }}
          accessibilityHint={t('licences.toggleHint')}
          onPress={() => toggle(item.name)}
          style={({ pressed }) => [
            styles.row,
            {
              minHeight: minTapTarget,
              paddingHorizontal: spacing.lg,
              paddingVertical: spacing.md,
              opacity: pressed ? 0.6 : 1,
            },
          ]}
        >
          <View style={styles.flex}>
            <Text style={{ color: colors.text, fontSize: fontSize.body, fontWeight: '600' }}>
              {item.name}
            </Text>
            <Text style={{ color: colors.textSecondary, fontSize: fontSize.caption }}>
              {t('licences.versionLicence', { version: item.version, licence: item.license })}
            </Text>
          </View>
          <Ionicons
            name={expanded ? 'chevron-up' : 'chevron-down'}
            size={20}
            color={colors.iconInactive}
          />
        </Pressable>
        {expanded && (
          <View style={{ paddingHorizontal: spacing.lg, paddingBottom: spacing.lg }}>
            {text !== null ? (
              <Text
                selectable
                style={{
                  color: colors.textSecondary,
                  fontSize: fontSize.caption,
                  fontFamily: MONOSPACE,
                  backgroundColor: colors.surfaceMuted,
                  borderRadius: radius.sm,
                  padding: spacing.md,
                }}
              >
                {text}
              </Text>
            ) : (
              <Pressable
                accessibilityRole="link"
                onPress={() =>
                  void Linking.openURL(
                    `https://www.npmjs.com/package/${item.name}/v/${item.version}`,
                  )
                }
                style={({ pressed }) => [
                  styles.row,
                  { minHeight: minTapTarget, gap: spacing.xs, opacity: pressed ? 0.6 : 1 },
                ]}
              >
                <Text
                  style={{
                    color: colors.text,
                    fontSize: fontSize.body,
                    textDecorationLine: 'underline',
                  }}
                >
                  {t('licences.npmLink')}
                </Text>
                <Ionicons name="open-outline" size={16} color={colors.textSecondary} />
              </Pressable>
            )}
          </View>
        )}
      </View>
    );
  };

  return (
    <SafeAreaView edges={['bottom']} style={[styles.flex, { backgroundColor: colors.background }]}>
      <FlashList
        data={licences.packages}
        extraData={open}
        keyExtractor={(item) => item.name}
        renderItem={renderItem}
        ListHeaderComponent={
          <Text
            style={{
              color: colors.text,
              fontSize: fontSize.body,
              padding: spacing.lg,
            }}
          >
            {t('licences.intro', { count: licences.packages.length })}
          </Text>
        }
        contentContainerStyle={{ paddingBottom: spacing.xxl }}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center' },
});
